# Generated by `scripts/build-tokens.mjs` — do not edit by hand.
# Edit the source at `design-tokens/<theme>.tokens.json` instead.
#
# Intended for ReportLab, which has no CSS parser and needs concrete Python values rather than a stylesheet

from reportlab.lib.colors import HexColor

COLOR_BLUE_50 = HexColor("#f0f7ff")
COLOR_BLUE_100 = HexColor("#e0efff")
COLOR_BLUE_200 = HexColor("#b9dcfe")
COLOR_BLUE_300 = HexColor("#7cb9e8")
COLOR_BLUE_400 = HexColor("#5aa3d9")
COLOR_BLUE_500 = HexColor("#3b82c4")
COLOR_BLUE_600 = HexColor("#2563a0")
COLOR_YELLOW_50 = HexColor("#fffdf0")
COLOR_YELLOW_300 = HexColor("#f5d76e")
COLOR_YELLOW_500 = HexColor("#d4a72c")
COLOR_GRAY_50 = HexColor("#fafbff")
COLOR_GRAY_200 = HexColor("#e2e8f0")
COLOR_GRAY_500 = HexColor("#64748b")
COLOR_GRAY_600 = HexColor("#475569")
COLOR_GRAY_800 = HexColor("#1e293b")
COLOR_GRAY_900 = HexColor("#0f172a")
COLOR_SEMANTIC_BACKGROUND = HexColor("#fafbff")
COLOR_SEMANTIC_BACKGROUND_ALT = HexColor("#f0f7ff")
COLOR_SEMANTIC_TEXT_PRIMARY = HexColor("#1e293b")
COLOR_SEMANTIC_TEXT_SECONDARY = HexColor("#475569")
COLOR_SEMANTIC_TEXT_MUTED = HexColor("#64748b")
COLOR_SEMANTIC_ACCENT = HexColor("#7cb9e8")
COLOR_SEMANTIC_ACCENT_WARM = HexColor("#f5d76e")
COLOR_SEMANTIC_BORDER = HexColor("#e2e8f0")
DIMENSION_RADIUS_SM = 6  # points
DIMENSION_RADIUS_MD = 12  # points
DIMENSION_RADIUS_LG = 20  # points
FONTFAMILY_SANS = ["Google Sans","-apple-system","Segoe UI","Roboto","Helvetica Neue","Arial","sans-serif"]
FONTFAMILY_SERIF = ["Crimson Pro","Georgia","Times New Roman","serif"]
FONTFAMILY_MONO = ["SF Mono","Cascadia Code","Fira Code","Consolas","monospace"]
