// Providing the shared building blocks for every Typst curriculum vitae
// generated by mcp-me. Deliberately avoiding `#grid` and `#table` for the
// overall page skeleton, since the ATS-parseability rationale recorded in
// `ats-score.ts` credits Typst's single-column, non-tabular output for its
// ranking above Pandoc's Chromium-mediated path.

#let heading-colour = rgb("#1a1a1a")
#let muted-colour = rgb("#5a5a5a")
#let rule-colour = rgb("#c9c9c9")

// Configuring the page, fonts, and heading style for the whole document,
// then yielding the body content passed by the caller.
#let cv-document(
  name: "",
  headline: "",
  location: "",
  email: "",
  website: "",
  body,
) = {
  set page(paper: "a4", margin: 2cm)
  set text(font: "Google Sans", size: 10.5pt, lang: "en")
  set heading(numbering: none)
  show heading.where(level: 1): it => {
    set text(size: 13pt, weight: "bold", fill: heading-colour)
    block(above: 1.2em, below: 0.6em)[
      #it.body
      #line(length: 100%, stroke: 0.5pt + rule-colour)
    ]
  }

  align(center)[
    #text(size: 20pt, weight: "bold", fill: heading-colour)[#name]
    #if headline != "" [
      #v(0.2em)
      #text(size: 11pt, fill: muted-colour, style: "italic")[#headline]
    ]
    #v(0.3em)
    #text(size: 9.5pt, fill: muted-colour)[
      #(location, email, website).filter(s => s != "").join("  ·  ")
    ]
  ]

  v(0.8em)
  body
}

// Rendering a single dated entry (an experience or education record) as
// stacked, left-aligned text rather than as a two-column table, keeping
// the reading order identical to the document order an ATS parser walks.
#let cv-entry(dates: "", title: "", org: "", location: "", body) = {
  block(above: 0.6em, below: 0.6em)[
    #text(weight: "bold")[#title] #h(0.4em) #text(fill: muted-colour)[--- #org]
    #linebreak()
    #text(size: 9pt, fill: muted-colour, style: "italic")[
      #(dates, location).filter(s => s != "").join("  ·  ")
    ]
    #v(0.3em)
    #body
  ]
}
