import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { basename, join } from "node:path";

/**
 * A minimal implementation of the W3C Design Tokens Community Group (W3C DTCG) format: nodes carrying `$value` and `$type` are tokens, everything else is a group. `$value` strings of the form `{a.b.c}` are aliases, resolved recursively against the same tree, so a semantic token such as `color.semantic.accent` need never duplicate the raw hexadecimal value that `color.blue.300` already states once
 */

const ALIAS_PATTERN = /^\{([a-zA-Z0-9.-]+)\}$/;

function isToken(node) {
  return node && typeof node === "object" && "$value" in node;
}

function getByPath(tree, path) {
  const parts = path.split(".");
  let node = tree;
  for (const part of parts) {
    if (node == null || typeof node !== "object") return undefined;
    node = node[part];
  }
  return node;
}

function resolveValue(tree, value, seenPaths = []) {
  if (typeof value === "string") {
    const match = ALIAS_PATTERN.exec(value);
    if (match) {
      const aliasPath = match[1];
      if (seenPaths.includes(aliasPath)) {
        throw new Error(`Circular alias detected: ${[...seenPaths, aliasPath].join(" -> ")}`);
      }
      const target = getByPath(tree, aliasPath);
      if (!isToken(target)) {
        throw new Error(`Alias "{${aliasPath}}" does not resolve to a token`);
      }
      return resolveValue(tree, target.$value, [...seenPaths, aliasPath]);
    }
    return value;
  }
  if (Array.isArray(value)) {
    return value.map((v) => resolveValue(tree, v, seenPaths));
  }
  return value;
}

export function flattenTokens(tree, prefix = [], root = tree) {
  const results = [];
  for (const [key, node] of Object.entries(tree)) {
    if (key.startsWith("$")) continue;
    const path = [...prefix, key];
    if (isToken(node)) {
      results.push({
        path: path.join("."),
        type: node.$type,
        value: resolveValue(root, node.$value),
      });
    } else if (node && typeof node === "object") {
      results.push(...flattenTokens(node, path, root));
    }
  }
  return results;
}

function toKebabCase(path) {
  return path.replace(/\./g, "-");
}

function toCamelCase(path) {
  const words = path.split(/[.-]/);
  return words
    .map((word, i) => (i === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1)))
    .join("")
    .replace(/[^a-zA-Z0-9]/g, "");
}

function toPascalCase(path) {
  const camel = toCamelCase(path);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function toPythonConstant(path) {
  return path.replace(/\./g, "_").replace(/-/g, "_").toUpperCase();
}

export function emitCss(tokens) {
  const lines = [
    "/* Generated by `scripts/build-tokens.mjs` — do not edit by hand.",
    "   Edit the source at `design-tokens/<theme>.tokens.json` instead. */",
    ":root {",
  ];

  for (const t of tokens) {
    if (t.type === "color" || t.type === "dimension") {
      lines.push(`  --${toKebabCase(t.path)}: ${t.value};`);
    } else if (t.type === "fontFamily") {
      lines.push(`  --${toKebabCase(t.path)}: ${t.value.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", ")};`);
    }
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

export function emitLatex(tokens) {
  const lines = [
    "% Generated by `scripts/build-tokens.mjs` — do not edit by hand.",
    "% Edit the source at `design-tokens/<theme>.tokens.json` instead.",
  ];

  for (const t of tokens) {
    if (t.type === "color") {
      const hex = t.value.replace("#", "").toUpperCase();
      lines.push(`\\definecolor{${toCamelCase(t.path)}}{HTML}{${hex}}`);
    } else if (t.type === "fontFamily") {
      lines.push(`% ${t.path}: ${t.value[0]} (first family member; LaTeX selects one concrete font, not a fallback stack)`);
    }
  }

  return lines.join("\n") + "\n";
}

export function emitTypst(tokens) {
  const lines = [
    "// Generated by `scripts/build-tokens.mjs` — do not edit by hand.",
    "// Edit the source at `design-tokens/<theme>.tokens.json` instead.",
    "#let tokens = (",
  ];

  for (const t of tokens) {
    if (t.type === "color") {
      lines.push(`  "${t.path}": rgb("${t.value}"),`);
    } else if (t.type === "dimension") {
      lines.push(`  "${t.path}": ${parseFloat(t.value)}pt,`);
    } else if (t.type === "fontFamily") {
      lines.push(`  "${t.path}": "${t.value[0]}",`);
    }
  }
  lines.push(")");
  return lines.join("\n") + "\n";
}

export function emitPython(tokens) {
  const lines = [
    "# Generated by `scripts/build-tokens.mjs` — do not edit by hand.",
    "# Edit the source at `design-tokens/<theme>.tokens.json` instead.",
    "#",
    "# Intended for ReportLab, which has no CSS parser and needs concrete Python values rather than a stylesheet",
    "",
    "from reportlab.lib.colors import HexColor",
    "",
  ];
  for (const t of tokens) {
    if (t.type === "color") {
      lines.push(`${toPythonConstant(t.path)} = HexColor("${t.value}")`);
    } else if (t.type === "dimension") {
      lines.push(`${toPythonConstant(t.path)} = ${parseFloat(t.value)}  # points`);
    } else if (t.type === "fontFamily") {
      lines.push(`${toPythonConstant(t.path)} = ${JSON.stringify(t.value)}`);
    }
  }
  return lines.join("\n") + "\n";
}

const THEME_NUMBERS = {
  clean: "01",
  modern: "03",
  standard: "04",
  "custom-01": "05",
  "custom-02": "06",
};

function main() {
  const themeArg = process.argv[2];
  if (!themeArg) {
    console.error("Usage: node scripts/build-tokens.mjs <theme-name>");
    process.exit(1);
  }
  const number = THEME_NUMBERS[themeArg];
  if (!number) {
    console.error(
      `Unknown theme "${themeArg}". Known themes: ${Object.keys(THEME_NUMBERS).join(", ")}. ` +
        "Add it to THEME_NUMBERS in this script first, matching the project's own numbering convention",
    );
    process.exit(1);
  }

  const sourcePath = join("design-tokens", `${themeArg}.tokens.json`);
  const tree = JSON.parse(readFileSync(sourcePath, "utf-8"));
  const tokens = flattenTokens(tree);

  const outputs = [
    ["assets/engines/html", `004-${number}-tokens-${themeArg}.css`, emitCss(tokens)],
    ["assets/engines/latex", `004-${number}-tokens-${themeArg}.sty`, emitLatex(tokens)],
    ["assets/engines/typst", `004-${number}-tokens-${themeArg}.typ`, emitTypst(tokens)],
    ["assets/engines/python", `tokens_${themeArg}.py`, emitPython(tokens)],
  ];

  for (const [dir, filename, content] of outputs) {
    mkdirSync(dir, { recursive: true });
    const outPath = join(dir, filename);
    writeFileSync(outPath, content, "utf-8");
    console.log(`Written ${outPath} (${tokens.length} tokens)`);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
