# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-07-07T06:11:33+00:00

from __future__ import annotations

import datetime
from typing import Annotated, Optional

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel


class CustomBaseModel(BaseModel):
    model_config = ConfigDict(
        validate_by_alias=True,
        validate_by_name=True,
        alias_generator=to_camel,
    )


class CandidateName(CustomBaseModel):
    first_name: Optional[str] = None
    family_name: Optional[str] = None
    middle_name: Optional[str] = None
    preferred_given_name: Optional[str] = None
    suffix: Optional[str] = None
    title: Optional[str] = None


class EducationLevel(CustomBaseModel):
    value: str


class GradeUnit(CustomBaseModel):
    value: str


class EducationGrade(CustomBaseModel):
    grade_score: Optional[float] = None
    grade_unit: Optional[GradeUnit] = None


class WorkExperienceType(CustomBaseModel):
    value: str


class ProjectType(CustomBaseModel):
    value: str


class PublicationItem(CustomBaseModel):
    publication_title: Optional[str] = None
    publication_date: Optional[datetime.date] = None
    publication_journal_name: Optional[str] = None


class LanguageName(CustomBaseModel):
    label: str
    value: str


class LanguageProficiency(CustomBaseModel):
    value: str


class LanguageItem(CustomBaseModel):
    language_name: Optional[LanguageName] = None
    language_proficiency: Optional[LanguageProficiency] = None


class SkillItem(CustomBaseModel):
    name: str
    type: str
    emsi_id: str
    info_url: Optional[str] = None
    category: Optional[str] = None
    is_language: bool
    is_software: bool
    sub_category: Optional[str] = None


class UrlDPValue(CustomBaseModel):
    url: str
    domain: str


class PhoneNumberDetails(CustomBaseModel):
    raw_text: str
    formatted_number: Optional[str] = None
    country_code: Optional[str] = None
    international_country_code: Optional[int] = None
    national_number: Optional[str] = None


class Location(CustomBaseModel):
    formatted: Annotated[Optional[str], Field(max_length=256, title="Formatted")] = None
    street_number: Annotated[
        Optional[str], Field(max_length=100, title="Street number")
    ] = None
    street: Annotated[Optional[str], Field(max_length=100, title="Street")] = None
    apartment_number: Annotated[
        Optional[str], Field(max_length=100, title="Apartment number")
    ] = None
    city: Annotated[Optional[str], Field(max_length=100, title="City")] = None
    postal_code: Annotated[
        Optional[str], Field(max_length=100, title="Postal code")
    ] = None
    state: Annotated[Optional[str], Field(max_length=100, title="State")] = None
    state_code: Annotated[Optional[str], Field(max_length=10, title="State code")] = (
        None
    )
    country: Annotated[Optional[str], Field(max_length=100, title="Country")] = None
    raw_input: Annotated[Optional[str], Field(max_length=256, title="Raw input")] = None
    country_code: Annotated[
        Optional[str], Field(max_length=3, title="Country code")
    ] = None
    latitude: Annotated[Optional[float], Field(title="Latitude")] = None
    longitude: Annotated[Optional[float], Field(title="Longitude")] = None
    place_id: Annotated[Optional[str], Field(min_length=1, title="Place id")] = None
    po_box: Annotated[Optional[str], Field(max_length=100, title="Po box")] = None


class Date(CustomBaseModel):
    date: Optional[datetime.date] = None
    is_current: Optional[bool] = False
    day: Optional[int] = None
    month: Optional[int] = None
    year: Optional[int] = None


class RefereeItem(CustomBaseModel):
    referee_name: Optional[str] = None
    referee_email: Optional[str] = None
    referee_job_title: Optional[str] = None
    referee_organization: Optional[str] = None
    referee_phone: Optional[PhoneNumberDetails] = None


class DateRange(CustomBaseModel):
    start: Optional[Date] = None
    end: Optional[Date] = None


class EducationItem(CustomBaseModel):
    education_minor: Optional[list[Optional[str]]] = None
    education_accreditation: Optional[str] = None
    education_level: Optional[EducationLevel] = None
    education_organization: Optional[str] = None
    education_location: Optional[Location] = None
    education_major: Optional[list[Optional[str]]] = None
    education_dates: Optional[DateRange] = None
    education_grade: Optional[EducationGrade] = None


class WorkExperienceItem(CustomBaseModel):
    work_experience_job_title: Optional[str] = None
    work_experience_organization: Optional[str] = None
    work_experience_location: Optional[Location] = None
    work_experience_dates: Optional[DateRange] = None
    work_experience_description: Optional[str] = None
    work_experience_type: Optional[WorkExperienceType] = None


class ProjectItem(CustomBaseModel):
    project_title: Optional[str] = None
    project_description: Optional[str] = None
    project_dates: Optional[DateRange] = None
    project_organization: Optional[str] = None
    project_type: Optional[ProjectType] = None


class Resume(CustomBaseModel):
    website: Optional[list[UrlDPValue]] = None
    candidate_name: Optional[CandidateName] = None
    date_of_birth: Optional[datetime.date] = None
    headshot: Optional[str] = None
    nationality: Optional[list[Optional[str]]] = None
    email: Optional[list[Optional[str]]] = None
    phone_number: Optional[list[PhoneNumberDetails]] = None
    location: Optional[Location] = None
    availability: Optional[str] = None
    preferred_work_location: Optional[Location] = None
    willing_to_relocate: Optional[bool] = None
    objective: Optional[str] = None
    summary: Optional[str] = None
    expected_salary: Optional[str] = None
    education: Optional[list[EducationItem]] = None
    work_experience: Optional[list[WorkExperienceItem]] = None
    total_years_experience: Optional[float] = None
    project: Optional[list[ProjectItem]] = None
    achievement: Optional[list[Optional[str]]] = None
    association: Optional[list[Optional[str]]] = None
    hobby: Optional[list[Optional[str]]] = None
    patent: Optional[list[Optional[str]]] = None
    publication: Optional[list[PublicationItem]] = None
    right_to_work: Optional[str] = None
    referee: Optional[list[RefereeItem]] = None
    language: Optional[list[LanguageItem]] = None
    skill: Optional[list[SkillItem]] = None
